[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emulation = { path = "../emulation" }
rodio = { version = "0.17.3" }
sdl2 = "0.36.0"
